 
export const LApi:any = {
    user:{
        get:`/admin/user/list`,
        post:`/admin/user/create`,
        update:`/admin/user/`,
        delete:`/admin/user/`,
        getbyId:`/admin/user/`
        
    },
    country:{
        get:`/admin/country/list`,
        post:`/admin/country/create`,
        update:`/admin/country/`,
        delete:`/admin/country/`,
        getbyId:`/admin/country/`
    },
    ['admin-meeting']:{
      get:`/admin/meeting/list`,
      getbyId:`/admin/meeting/`
    },
    ['moderator-meeting']:{
        get:`/moderator/meeting/list`,
        post:`/moderator/meeing/create`,
        delete:`/moderator/meeting/`,
        update:`/moderator/meeting/`,
        getbyId:`/moderator/meeting/`
    },
    ['viewer-meeting']:{
        get:`/viewer/meeting/list`,
        getbyId:`/viewer/meeting/`
    },
    region:{
        get:`/region/list`,
        post:`/region/create`,
        update:`/region/update`,
        delete:`/region/`,
        getbyId:`/region/`

    },
    ['project-field']:{
        get:`/project-field/list`,
        post:`/project-field/create`,
        update:`/project-field/update`,
        delete:`/project-field/`,
        getbyId:`/project-field/`
    },
    project:{
        get:`/project/list`,
        post:`/project/create`,
        update:`/project/update`,
        delete:`/project/`,
        getbyId:`/project/`
    },
    commentary:{
        get:`/commentary/list`,
        delete:`/commentary/`,
        getbyId:`/commentary`,
        update:`/commentary/update`
    },
    work:{
        get:`/work/list`,
        post:`/work/create`,
        update:`/work/`,
        delete:`/work/`,
        getbyId:`/work`
    },
    ['meeting-description']:{
        get:`/viewer/meeting-description/list/`,
        post:`/work/create`,
        update:`/work/`,
        delete:`/work/`,
        getbyId:`/viewer/meeting-description`
    },
    ['admin-partner']:{
        get:`/admin/partner/list`,
        post:`/admin/partner/create`,
        getbyId:`/admin/partner/`,
        delete:`/admin/partner/`,
        update:`/admin/partner/`
    },
     ['worker-partner']:{
        get:`/worker/partner/list`,
        post:`/worker/partner/create`,
        getbyId:`/worker/partner/`,
        delete:`/worker/partner/`,
        update:`/worker/partner/`
    }
}


export const LModule = ['user']